version: '3'
services:

  # Dependencies
  #

  elasticsearch:
    stdin_open: true
    tty: true
    image: elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    ports:
    - 9200:9200

  mysql:
    stdin_open: true
    tty: true
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=particular
    ports:
    - 3306:3306

  redis:
    stdin_open: true
    tty: true
    image: redis:5.0.7
    ports:
    - 6379:6379
